#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Mar 24 15:11:37 EDT 2025
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim controller_test_behav -key {Behavioral:sim_1:Functional:controller_test} -tclbatch controller_test.tcl -log simulate.log"
xsim controller_test_behav -key {Behavioral:sim_1:Functional:controller_test} -tclbatch controller_test.tcl -log simulate.log

